on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - run: docker info
    - run: cat /etc/os-release
    - run: uname -a
    - name: Run apt update on Ubuntu:jammy
      run: docker run ubuntu@sha256:7599221e4e2e4eeb90ad282fc523139578f3dfea245b5049c4fee1b28776d2be apt update
